version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
    - "8080:80"
    volumes:
    - ./src:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
    - ./src:/var/www/html
    ports:
    - "9000:9000"
    networks:
      - laravel

  mysql:
    image: mariadb:latest
    container_name: mysql
    restart: always
    tty: true
    ports:
    - "3306:3306"
    volumes:
    - ./mysqldb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    networks:
      - laravel